# Generated by Django 5.1.2 on 2024-10-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_categories_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
